name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cargo
            target
          key: build-${{ runner.os }}
          restore-keys: |
            build-${{ runner.os }}
      - run: cargo build
  lint:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cargo
            target
          key: build-${{ runner.os }}
          restore-keys: |
            build-${{ runner.os }}
      - run: cargo clippy --all-targets
  test:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cargo
            target
          key: build-${{ runner.os }}
          restore-keys: |
            build-${{ runner.os }}
      - run: cargo test
