name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_FLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.2.6
        with:
          path: |
            ~/.cargo
            target
          key: build-${{ runner.os }}
          restore-keys: |
            build-${{ runner.os }}
      - name: Lint
        run: cargo clippy --all-targets
      - name: Test
        run: cargo test
